name: Get Citation Data

on:
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '0 8 * * *' # 每天北京时间 16:00 运行
  workflow_dispatch:      # 允许你在 Actions 页面手动点击按钮运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # 使用最新的 checkout 版本

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-setuptools
          if [ -f google_scholar_crawler/requirements.txt ]; then
            pip3 install -r google_scholar_crawler/requirements.txt
          fi

      - name: Run Crawler
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd ./google_scholar_crawler
          python3 main.py

      - name: Push Data to Branch
        run: |
          # 进入数据结果目录
          cd ./google_scholar_crawler/results 
          
          # 初始化并推送到单独的分支 google-scholar-stats
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # 这里的 remote_repo 会自动使用仓库自带的 GITHUB_TOKEN
          export remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          
          git add *.json
          git commit -m "Updated Citation Data at $(date)"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
